[package]
name = "galaxy"
version = "0.1.0"
authors = ["iona <arthur.blanleuil@inria.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
las = "0.7.1"
rand = "0.7.3"
petgraph = "0.5.1"
